export const GETSLIDELIST = 'GETSLIDELIST';
export const SETSLIDELIST = 'SETSLIDELIST';
export const GETBIGKALIST = 'GETBIGKALIST';
export const SETBIGKALIST = 'SETBIGKALIST';
export const SETDATELIST = 'SETDATELIST';
export const SETPROJECT = 'SETPROJECT';
export const CHGOPEN = 'CHGOPEN';
export const DISTANCE = 'DISTANCE';
